#!/usr/bin/env node

/**
 * Scene Backup Script for AI Transmission Navigator
 * 
 * This script captures the current scene data from localStorage and creates backup files.
 * Run this script in the project root or use browser console to capture scenes.
 */

const fs = require('fs');
const path = require('path');

// Configuration
const STORAGE_KEY = 'transmissionScenes'; // Update this to match your app's storage key
const BACKUP_DIR = './backups';
const README_FILE = 'SCENE_BACKUP_README.md';

// Ensure backup directory exists
if (!fs.existsSync(BACKUP_DIR)) {
  fs.mkdirSync(BACKUP_DIR, { recursive: true });
}

function getCurrentTimestamp() {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
}

function generateREADME(scenes, timestamp) {
  const sceneCount = scenes.length;
  const sampleScene = scenes[0] || {};
  
  return `# AI Transmission Navigator - Scene Backup

## Backup Information
- **Created**: ${new Date().toISOString()}
- **Scene Count**: ${sceneCount}
- **Storage Key**: \`${STORAGE_KEY}\`

## Scene Data Structure
\`\`\`json
${JSON.stringify(sampleScene, null, 2)}
\`\`\`

## Restoration Methods

### Method 1: Browser Console (Recommended)
1. Open your application in the browser
2. Open Developer Tools (F12)
3. Go to Console tab
4. Paste the following code:

\`\`\`javascript
// Restore scenes from backup
const CAPTURED_SCENES = ${JSON.stringify(scenes, null, 2)};

// Clear existing scenes and restore backup
localStorage.setItem('${STORAGE_KEY}', JSON.stringify(CAPTURED_SCENES));

// Refresh page to load restored scenes
location.reload();
\`\`\`

### Method 2: Manual Recreation via Map Controls
Each scene can be manually recreated using these parameters:

${scenes.map((scene, index) => `
#### Scene ${index + 1}: "${scene.name}"
- **Camera Position**: 
  - Center: [${scene.camera?.center?.lng || 0}, ${scene.camera?.center?.lat || 0}]
  - Zoom: ${scene.camera?.zoom || 10}
  - Pitch: ${scene.camera?.pitch || 0}
  - Bearing: ${scene.camera?.bearing || 0}

- **Layer Visibility**:
${Object.entries(scene.layerState || {}).map(([key, value]) => `  - ${key}: ${value}`).join('\n')}

- **Map Layer States**:
${Object.entries(scene.mapLayerStates || {}).map(([key, value]) => `  - ${key}: ${value}`).join('\n')}
`).join('\n')}

### Method 3: Programmatic Restoration
\`\`\`javascript
// Import scenes in your application
const importScenes = (scenes) => {
  scenes.forEach(scene => {
    // Apply camera position
    map.easeTo({
      center: [scene.camera.center.lng, scene.camera.center.lat],
      zoom: scene.camera.zoom,
      pitch: scene.camera.pitch,
      bearing: scene.camera.bearing,
      duration: 2000
    });
    
    // Apply layer visibility
    Object.entries(scene.layerState).forEach(([layerKey, isVisible]) => {
      // Your layer toggle logic here
      toggleLayer(layerKey, isVisible);
    });
    
    // Apply map layer states
    Object.entries(scene.mapLayerStates).forEach(([layerId, isVisible]) => {
      if (map.getLayer(layerId)) {
        map.setLayoutProperty(layerId, 'visibility', isVisible ? 'visible' : 'none');
      }
    });
  });
};
\`\`\`

## Scene List
${scenes.map((scene, index) => `${index + 1}. **${scene.name}** (ID: ${scene.id}) - ${scene.timestamp}`).join('\n')}

## Notes
- Always backup your scenes before major updates
- Test restoration in a development environment first
- Scene IDs are timestamp-based and should remain unique
- Layer states may need adjustment if layer structure changes

---
*Generated by AI Transmission Navigator Scene Backup Script*
`;
}

function captureScenes() {
  console.log('🎬 AI Transmission Navigator Scene Backup');
  console.log('==========================================');
  
  // In a real browser environment, you would read from localStorage
  // For this script, we'll provide instructions for manual capture
  
  const timestamp = getCurrentTimestamp();
  const readmePath = path.join(BACKUP_DIR, README_FILE);
  
  // Create a sample structure for documentation
  const sampleScenes = [
    {
      id: "1234567890123",
      name: "Sample Scene",
      timestamp: "2024-01-01T12:00:00.000Z",
      camera: {
        center: { lng: -100.0, lat: 31.0 },
        zoom: 10,
        pitch: 0,
        bearing: 0
      },
      layerState: {
        "transmission": true,
        "generation": false,
        "demand": true
      },
      mapLayerStates: {
        "transmission-lines": true,
        "generation-points": false
      },
      customState: {}
    }
  ];
  
  // Generate README with instructions
  const readmeContent = generateREADME(sampleScenes, timestamp);
  fs.writeFileSync(readmePath, readmeContent);
  
  console.log(`📝 Generated backup README: ${readmePath}`);
  console.log('');
  console.log('📋 To capture actual scenes:');
  console.log('1. Open your application in the browser');
  console.log('2. Open Developer Tools (F12) → Console');
  console.log('3. Run: localStorage.getItem("transmissionScenes")');
  console.log('4. Copy the output and save it as a backup file');
  console.log('');
  console.log('🔄 To restore scenes:');
  console.log('1. Use the browser console method in the generated README');
  console.log('2. Or use the programmatic restoration examples');
  
  return true;
}

// Run if called directly
if (require.main === module) {
  try {
    captureScenes();
    console.log('✅ Scene backup process completed successfully');
  } catch (error) {
    console.error('❌ Error during scene backup:', error);
    process.exit(1);
  }
}

module.exports = { captureScenes, generateREADME };