/**
 * Default Scenes Loader
 * Automatically loads default scenes when the app starts
 */

// Default scenes data (extracted from the backup)
const DEFAULT_SCENES = [
  {
    "id": "1753970378975",
    "name": "1",
    "timestamp": "2025-07-31T15:06:27.895Z",
    "layerState": {
      "showTransportation": false,
      "showRoads": true,
      "showParks": true,
      "showFortStocktonRadius": false,
      "showKeyInfrastructure": false,
      "showOSMTransit": false,
      "showTransitStops": false,
      "showTransitRoutes": false,
      "showMainPathA": false,
      "showMainPathB": false,
      "showMainPathAA": false,
      "showMainRoads": false,
      "showSources": false,
      "showBlocks": true,
      "showBlockFill": true,
      "showDataCenters": false,
      "showDemand": false,
      "showSupply": false,
      "showWater": false,
      "showAquiferZones": false,
      "showNewMajorAquifers": false,
      "showHUC8Subbasin": false,
      "showTWDBGroundwater": false
    },
    "camera": {
      "center": {
        "lng": -102.36939656649214,
        "lat": 30.532851502401016
      },
      "zoom": 6.288546523766031,
      "pitch": 0,
      "bearing": 0
    },
    "mapLayerStates": {
      "land": true,
      "national-park": true,
      "landuse": true,
      "waterway": true,
      "water": true,
      "land-structure-polygon": true,
      "land-structure-line": true,
      "aeroway-polygon": true,
      "aeroway-line": true,
      "building": true,
      "tunnel-path-trail": true,
      "tunnel-path-cycleway-piste": true,
      "tunnel-path": true,
      "tunnel-steps": true,
      "tunnel-pedestrian": true,
      "tunnel-simple": true,
      "road-path-trail": true,
      "road-path-cycleway-piste": true,
      "road-path": true,
      "road-steps": true,
      "road-pedestrian": true,
      "road-simple": true,
      "road-rail": true,
      "bridge-path-trail": true,
      "bridge-path-cycleway-piste": true,
      "bridge-path": true,
      "bridge-steps": true,
      "bridge-pedestrian": true,
      "bridge-case-simple": true,
      "bridge-simple": true,
      "bridge-rail": true,
      "admin-1-boundary-bg": true,
      "admin-0-boundary-bg": true,
      "admin-1-boundary": true,
      "admin-0-boundary": true,
      "admin-0-boundary-disputed": true,
      "road-label-simple": true,
      "waterway-label": true,
      "natural-line-label": true,
      "natural-point-label": true,
      "water-line-label": true,
      "water-point-label": true,
      "poi-label": true,
      "airport-label": true,
      "settlement-subdivision-label": true,
      "settlement-minor-label": true,
      "settlement-major-label": true,
      "state-label": true,
      "country-label": true,
      "continent-label": true,
      "huc8-subbasin-layer": false,
      "twdb-groundwater-layer": false,
      "osm-transit-stops": false,
      "osm-transit-routes": false,
      "osm-bike-lanes": false,
      "osm-bike-paths": false,
      "osm-bike-parking": false,
      "osm-pedestrian-paths": false,
      "osm-pedestrian-crossings": false,
      "road-particles": true,
      "census-blocks": false,
      "osm-buildings": true,
      "mapbox-buildings": true,
      "mud-districts": false,
      "surface-water": false,
      "surface-water-intake": false,
      "small-tribal-areas": false,
      "small-areas": false,
      "pws-reservoir": false,
      "waterwell-grid": false,
      "wastewater-outfalls": false,
      "zipcodes": false,
      "zipcode-flood-analysis": false,
      "ai-consensus-particles": false,
      "texas-block-fill-layer": true,
      "texas-block-fill-hover-layer": true,
      "texas-blocks-line-layer": true,
      "texas-blocks-hover-layer": true,
      "texas-blocks-fill-hover-layer": true
    },
    "customState": {
      "transmissionFocus": true,
      "analysisType": "transmission",
      "timestamp": 1753974387895
    }
  },
  {
    "id": "1753970403709",
    "name": "2",
    "timestamp": "2025-07-31T15:08:36.877Z",
    "layerState": {
      "showTransportation": false,
      "showRoads": true,
      "showParks": true,
      "showFortStocktonRadius": false,
      "showKeyInfrastructure": true,
      "showOSMTransit": false,
      "showTransitStops": false,
      "showTransitRoutes": false,
      "showMainPathA": true,
      "showMainPathB": true,
      "showMainPathAA": true,
      "showMainRoads": false,
      "showSources": true,
      "showBlocks": true,
      "showBlockFill": true,
      "showDataCenters": true,
      "showDemand": true,
      "showSupply": true,
      "showWater": true,
      "showAquiferZones": false,
      "showNewMajorAquifers": true,
      "showHUC8Subbasin": false,
      "showTWDBGroundwater": false
    },
    "camera": {
      "center": {
        "lng": -100.9355082154337,
        "lat": 30.44167057745382
      },
      "zoom": 6.924468961822629,
      "pitch": 38.03196760615904,
      "bearing": -15.52734828706889
    },
    "mapLayerStates": {
      "land": true,
      "national-park": true,
      "landuse": true,
      "waterway": true,
      "water": true,
      "land-structure-polygon": true,
      "land-structure-line": true,
      "aeroway-polygon": true,
      "aeroway-line": true,
      "building": true,
      "tunnel-path-trail": true,
      "tunnel-path-cycleway-piste": true,
      "tunnel-path": true,
      "tunnel-steps": true,
      "tunnel-pedestrian": true,
      "tunnel-simple": true,
      "road-path-trail": true,
      "road-path-cycleway-piste": true,
      "road-path": true,
      "road-steps": true,
      "road-pedestrian": true,
      "road-simple": true,
      "road-rail": true,
      "bridge-path-trail": true,
      "bridge-path-cycleway-piste": true,
      "bridge-path": true,
      "bridge-steps": true,
      "bridge-pedestrian": true,
      "bridge-case-simple": true,
      "bridge-simple": true,
      "bridge-rail": true,
      "admin-1-boundary-bg": true,
      "admin-0-boundary-bg": true,
      "admin-1-boundary": true,
      "admin-0-boundary": true,
      "admin-0-boundary-disputed": true,
      "road-label-simple": true,
      "waterway-label": true,
      "natural-line-label": true,
      "natural-point-label": true,
      "water-line-label": true,
      "water-point-label": true,
      "poi-label": true,
      "airport-label": true,
      "settlement-subdivision-label": true,
      "settlement-minor-label": true,
      "settlement-major-label": true,
      "state-label": true,
      "country-label": true,
      "continent-label": true,
      "huc8-subbasin-layer": false,
      "twdb-groundwater-layer": false,
      "osm-transit-stops": false,
      "osm-transit-routes": false,
      "osm-bike-lanes": false,
      "osm-bike-paths": false,
      "osm-bike-parking": false,
      "osm-pedestrian-paths": false,
      "osm-pedestrian-crossings": false,
      "road-particles": true,
      "census-blocks": false,
      "osm-buildings": true,
      "mapbox-buildings": true,
      "mud-districts": false,
      "surface-water": false,
      "surface-water-intake": false,
      "small-tribal-areas": false,
      "small-areas": false,
      "pws-reservoir": false,
      "waterwell-grid": false,
      "wastewater-outfalls": false,
      "zipcodes": false,
      "zipcode-flood-analysis": false,
      "ai-consensus-particles": false,
      "texas-block-fill-layer": true,
      "texas-block-fill-hover-layer": true,
      "texas-blocks-line-layer": true,
      "texas-blocks-hover-layer": true,
      "texas-blocks-fill-hover-layer": true,
      "main-path-a-layer": true,
      "main-path-a-circles-layer": true,
      "main-path-a-san-antonio-circles-layer": true,
      "main-path-a-circles-fill-layer": true,
      "main-path-a-san-antonio-circles-fill-5-layer": true,
      "main-path-a-san-antonio-circles-fill-15-layer": true,
      "main-path-a-san-antonio-circles-fill-30-layer": true,
      "main-path-a-circles-label-layer": true,
      "main-path-b-circles-layer": true,
      "main-path-b-circles-large-layer": true,
      "main-path-b-circles-label-layer": true,
      "main-christoval-circle-layer": true,
      "main-bigspring-circle-layer": true,
      "main-circle-markers-layer": true,
      "main-castroville-pulse-layer": true,
      "main-fort-stockton-pulse-layer": true,
      "main-path-b-layer": true,
      "main-path-aa-particles-layer": true,
      "sources-circle-fill-layer": true,
      "sources-circle-layer": true,
      "sources-layer": true,
      "sources-label-layer": true,
      "sources-pulse-layer": true,
      "key-infra-hs-layer": true,
      "data-centers-fill-layer": true,
      "data-centers-line-layer": true,
      "data-centers-point-layer": true,
      "data-centers-circles-fill-layer": true,
      "data-centers-circles-5mi-fill-layer": true,
      "demand-layer": true,
      "supply-layer": true,
      "water-layer": true,
      "new-major-aquifers-fill-layer": true,
      "new-major-aquifers-outline-layer": true
    },
    "customState": {
      "transmissionFocus": true,
      "analysisType": "transmission",
      "timestamp": 1753974516878
    }
  },
  {
    "id": "1753970437110",
    "name": "3",
    "timestamp": "2025-07-31T15:11:15.850Z",
    "layerState": {
      "showTransportation": false,
      "showRoads": true,
      "showParks": true,
      "showFortStocktonRadius": false,
      "showKeyInfrastructure": true,
      "showOSMTransit": false,
      "showTransitStops": false,
      "showTransitRoutes": false,
      "showMainPathA": true,
      "showMainPathB": true,
      "showMainPathAA": true,
      "showMainRoads": false,
      "showSources": false,
      "showBlocks": true,
      "showBlockFill": true,
      "showDataCenters": true,
      "showDemand": true,
      "showSupply": true,
      "showWater": true,
      "showAquiferZones": false,
      "showNewMajorAquifers": true,
      "showHUC8Subbasin": true,
      "showTWDBGroundwater": true
    },
    "camera": {
      "center": {
        "lng": -98.82136753288427,
        "lat": 29.435594942895264
      },
      "zoom": 9.65075572699547,
      "pitch": 39.0338890976057,
      "bearing": 32.47757073103446
    },
    "mapLayerStates": {
      "land": true,
      "national-park": true,
      "landuse": true,
      "waterway": true,
      "water": true,
      "land-structure-polygon": true,
      "land-structure-line": true,
      "aeroway-polygon": true,
      "aeroway-line": true,
      "building": true,
      "tunnel-path-trail": true,
      "tunnel-path-cycleway-piste": true,
      "tunnel-path": true,
      "tunnel-steps": true,
      "tunnel-pedestrian": true,
      "tunnel-simple": true,
      "road-path-trail": true,
      "road-path-cycleway-piste": true,
      "road-path": true,
      "road-steps": true,
      "road-pedestrian": true,
      "road-simple": true,
      "road-rail": true,
      "bridge-path-trail": true,
      "bridge-path-cycleway-piste": true,
      "bridge-path": true,
      "bridge-steps": true,
      "bridge-pedestrian": true,
      "bridge-case-simple": true,
      "bridge-simple": true,
      "bridge-rail": true,
      "admin-1-boundary-bg": true,
      "admin-0-boundary-bg": true,
      "admin-1-boundary": true,
      "admin-0-boundary": true,
      "admin-0-boundary-disputed": true,
      "road-label-simple": true,
      "waterway-label": true,
      "natural-line-label": true,
      "natural-point-label": true,
      "water-line-label": true,
      "water-point-label": true,
      "poi-label": true,
      "airport-label": true,
      "settlement-subdivision-label": true,
      "settlement-minor-label": true,
      "settlement-major-label": true,
      "state-label": true,
      "country-label": true,
      "continent-label": true,
      "huc8-subbasin-layer": true,
      "twdb-groundwater-layer": true,
      "osm-transit-stops": false,
      "osm-transit-routes": false,
      "osm-bike-lanes": false,
      "osm-bike-paths": false,
      "osm-bike-parking": false,
      "osm-pedestrian-paths": false,
      "osm-pedestrian-crossings": false,
      "road-particles": true,
      "census-blocks": false,
      "osm-buildings": true,
      "mapbox-buildings": true,
      "mud-districts": false,
      "surface-water": false,
      "surface-water-intake": false,
      "small-tribal-areas": false,
      "small-areas": false,
      "pws-reservoir": false,
      "waterwell-grid": false,
      "wastewater-outfalls": false,
      "zipcodes": false,
      "zipcode-flood-analysis": false,
      "ai-consensus-particles": false,
      "texas-blocks-line-layer": true,
      "texas-blocks-hover-layer": true,
      "texas-block-fill-layer": true,
      "texas-blocks-fill-hover-layer": true,
      "texas-block-fill-hover-layer": true,
      "main-path-a-layer": true,
      "main-path-a-circles-layer": true,
      "main-path-a-san-antonio-circles-layer": true,
      "main-path-a-circles-fill-layer": true,
      "main-path-a-san-antonio-circles-fill-5-layer": true,
      "main-path-a-san-antonio-circles-fill-15-layer": true,
      "main-path-a-san-antonio-circles-fill-30-layer": true,
      "main-path-a-circles-label-layer": true,
      "main-path-b-circles-layer": true,
      "main-path-b-circles-large-layer": true,
      "main-path-b-circles-label-layer": true,
      "main-christoval-circle-layer": true,
      "main-bigspring-circle-layer": true,
      "main-circle-markers-layer": true,
      "main-castroville-pulse-layer": true,
      "main-fort-stockton-pulse-layer": true,
      "key-infra-hs-layer": true,
      "data-centers-fill-layer": true,
      "data-centers-line-layer": true,
      "main-path-b-layer": true,
      "main-path-aa-particles-layer": true,
      "supply-layer": true,
      "demand-layer": true,
      "data-centers-point-layer": true,
      "data-centers-circles-fill-layer": true,
      "data-centers-circles-5mi-fill-layer": true,
      "new-major-aquifers-fill-layer": true,
      "new-major-aquifers-outline-layer": true,
      "water-layer": true
    },
    "customState": {
      "transmissionFocus": true,
      "analysisType": "transmission",
      "timestamp": 1753974675851
    }
  },
  {
    "id": "1753970440538",
    "name": "4",
    "timestamp": "2025-07-31T15:18:24.246Z",
    "layerState": {
      "showTransportation": false,
      "showRoads": true,
      "showParks": true,
      "showFortStocktonRadius": false,
      "showKeyInfrastructure": true,
      "showOSMTransit": false,
      "showTransitStops": false,
      "showTransitRoutes": false,
      "showMainPathA": true,
      "showMainPathB": true,
      "showMainPathAA": true,
      "showMainRoads": false,
      "showSources": true,
      "showBlocks": true,
      "showBlockFill": true,
      "showDataCenters": true,
      "showDemand": true,
      "showSupply": true,
      "showWater": true,
      "showAquiferZones": true,
      "showNewMajorAquifers": true,
      "showHUC8Subbasin": true,
      "showTWDBGroundwater": true
    },
    "camera": {
      "center": {
        "lng": -99.5626552841469,
        "lat": 30.10641196785062
      },
      "zoom": 7.227500635952921,
      "pitch": 50.745490384172854,
      "bearing": -125.38620888938487
    },
    "mapLayerStates": {
      "land": true,
      "national-park": true,
      "landuse": true,
      "waterway": true,
      "water": true,
      "land-structure-polygon": true,
      "land-structure-line": true,
      "aeroway-polygon": true,
      "aeroway-line": true,
      "building": true,
      "tunnel-path-trail": true,
      "tunnel-path-cycleway-piste": true,
      "tunnel-path": true,
      "tunnel-steps": true,
      "tunnel-pedestrian": true,
      "tunnel-simple": true,
      "road-path-trail": true,
      "road-path-cycleway-piste": true,
      "road-path": true,
      "road-steps": true,
      "road-pedestrian": true,
      "road-simple": true,
      "road-rail": true,
      "bridge-path-trail": true,
      "bridge-path-cycleway-piste": true,
      "bridge-path": true,
      "bridge-steps": true,
      "bridge-pedestrian": true,
      "bridge-case-simple": true,
      "bridge-simple": true,
      "bridge-rail": true,
      "admin-1-boundary-bg": true,
      "admin-0-boundary-bg": true,
      "admin-1-boundary": true,
      "admin-0-boundary": true,
      "admin-0-boundary-disputed": true,
      "road-label-simple": true,
      "waterway-label": true,
      "natural-line-label": true,
      "natural-point-label": true,
      "water-line-label": true,
      "water-point-label": true,
      "poi-label": true,
      "airport-label": true,
      "settlement-subdivision-label": true,
      "settlement-minor-label": true,
      "settlement-major-label": true,
      "state-label": true,
      "country-label": true,
      "continent-label": true,
      "huc8-subbasin-layer": true,
      "twdb-groundwater-layer": true,
      "osm-transit-stops": false,
      "osm-transit-routes": false,
      "osm-bike-lanes": false,
      "osm-bike-paths": false,
      "osm-bike-parking": false,
      "osm-pedestrian-paths": false,
      "osm-pedestrian-crossings": false,
      "road-particles": true,
      "census-blocks": false,
      "osm-buildings": true,
      "mapbox-buildings": true,
      "mud-districts": false,
      "surface-water": false,
      "surface-water-intake": false,
      "small-tribal-areas": false,
      "small-areas": false,
      "pws-reservoir": false,
      "waterwell-grid": false,
      "wastewater-outfalls": false,
      "zipcodes": false,
      "zipcode-flood-analysis": false,
      "ai-consensus-particles": false,
      "main-path-a-layer": true,
      "main-path-a-circles-layer": true,
      "main-path-a-san-antonio-circles-layer": true,
      "main-path-a-circles-fill-layer": true,
      "main-path-a-san-antonio-circles-fill-5-layer": true,
      "main-path-a-san-antonio-circles-fill-15-layer": true,
      "main-path-a-san-antonio-circles-fill-30-layer": true,
      "main-path-a-circles-label-layer": true,
      "main-path-b-circles-layer": true,
      "main-path-b-circles-large-layer": true,
      "main-path-b-circles-label-layer": true,
      "main-christoval-circle-layer": true,
      "main-bigspring-circle-layer": true,
      "main-circle-markers-layer": true,
      "main-castroville-pulse-layer": true,
      "main-fort-stockton-pulse-layer": true,
      "texas-blocks-line-layer": true,
      "texas-blocks-hover-layer": true,
      "texas-block-fill-layer": true,
      "key-infra-hs-layer": true,
      "main-path-b-layer": true,
      "main-path-aa-particles-layer": true,
      "data-centers-fill-layer": true,
      "data-centers-line-layer": true,
      "aquifer-zones-fill-layer": true,
      "aquifer-zones-outline-layer": true,
      "texas-blocks-fill-hover-layer": true,
      "texas-block-fill-hover-layer": true,
      "aquifer-zones-hover-outline-layer": true,
      "aquifer-zones-hover-layer": true,
      "data-centers-point-layer": true,
      "data-centers-circles-fill-layer": true,
      "data-centers-circles-5mi-fill-layer": true,
      "new-major-aquifers-fill-layer": true,
      "new-major-aquifers-outline-layer": true,
      "supply-layer": true,
      "demand-layer": true,
      "water-layer": true,
      "sources-circle-fill-layer": true,
      "sources-circle-layer": true,
      "sources-layer": true,
      "sources-label-layer": true,
      "sources-pulse-layer": true
    },
    "customState": {
      "transmissionFocus": true,
      "analysisType": "transmission",
      "timestamp": 1753975104247
    }
  },
  {
    "id": "1753970444612",
    "name": "5",
    "timestamp": "2025-07-31T15:17:40.333Z",
    "layerState": {
      "showTransportation": false,
      "showRoads": true,
      "showParks": true,
      "showFortStocktonRadius": false,
      "showKeyInfrastructure": true,
      "showOSMTransit": false,
      "showTransitStops": false,
      "showTransitRoutes": false,
      "showMainPathA": true,
      "showMainPathB": true,
      "showMainPathAA": true,
      "showMainRoads": true,
      "showSources": true,
      "showBlocks": true,
      "showBlockFill": true,
      "showDataCenters": true,
      "showDemand": false,
      "showSupply": true,
      "showWater": true,
      "showAquiferZones": true,
      "showNewMajorAquifers": true,
      "showHUC8Subbasin": true,
      "showTWDBGroundwater": true
    },
    "camera": {
      "center": {
        "lng": -102.92883935184125,
        "lat": 30.90692678533597
      },
      "zoom": 10.986936143681964,
      "pitch": 27.226216154736907,
      "bearing": 130.40052700248248
    },
    "mapLayerStates": {
      "land": true,
      "national-park": true,
      "landuse": true,
      "waterway": true,
      "water": true,
      "land-structure-polygon": true,
      "land-structure-line": true,
      "aeroway-polygon": true,
      "aeroway-line": true,
      "building": true,
      "tunnel-path-trail": true,
      "tunnel-path-cycleway-piste": true,
      "tunnel-path": true,
      "tunnel-steps": true,
      "tunnel-pedestrian": true,
      "tunnel-simple": true,
      "road-path-trail": true,
      "road-path-cycleway-piste": true,
      "road-path": true,
      "road-steps": true,
      "road-pedestrian": true,
      "road-simple": true,
      "road-rail": true,
      "bridge-path-trail": true,
      "bridge-path-cycleway-piste": true,
      "bridge-path": true,
      "bridge-steps": true,
      "bridge-pedestrian": true,
      "bridge-case-simple": true,
      "bridge-simple": true,
      "bridge-rail": true,
      "admin-1-boundary-bg": true,
      "admin-0-boundary-bg": true,
      "admin-1-boundary": true,
      "admin-0-boundary": true,
      "admin-0-boundary-disputed": true,
      "road-label-simple": true,
      "waterway-label": true,
      "natural-line-label": true,
      "natural-point-label": true,
      "water-line-label": true,
      "water-point-label": true,
      "poi-label": true,
      "airport-label": true,
      "settlement-subdivision-label": true,
      "settlement-minor-label": true,
      "settlement-major-label": true,
      "state-label": true,
      "country-label": true,
      "continent-label": true,
      "huc8-subbasin-layer": true,
      "twdb-groundwater-layer": true,
      "osm-transit-stops": false,
      "osm-transit-routes": false,
      "osm-bike-lanes": false,
      "osm-bike-paths": false,
      "osm-bike-parking": false,
      "osm-pedestrian-paths": false,
      "osm-pedestrian-crossings": false,
      "road-particles": true,
      "census-blocks": false,
      "osm-buildings": true,
      "mapbox-buildings": true,
      "mud-districts": false,
      "surface-water": false,
      "surface-water-intake": false,
      "small-tribal-areas": false,
      "small-areas": false,
      "pws-reservoir": false,
      "waterwell-grid": false,
      "wastewater-outfalls": false,
      "zipcodes": false,
      "zipcode-flood-analysis": false,
      "ai-consensus-particles": false,
      "main-path-a-layer": true,
      "main-path-a-circles-layer": true,
      "main-path-a-san-antonio-circles-layer": true,
      "main-path-a-circles-fill-layer": true,
      "main-path-a-san-antonio-circles-fill-5-layer": true,
      "main-path-a-san-antonio-circles-fill-15-layer": true,
      "main-path-a-san-antonio-circles-fill-30-layer": true,
      "main-path-a-circles-label-layer": true,
      "main-path-b-circles-layer": true,
      "main-path-b-circles-large-layer": true,
      "main-path-b-circles-label-layer": true,
      "main-christoval-circle-layer": true,
      "main-bigspring-circle-layer": true,
      "main-circle-markers-layer": true,
      "main-castroville-pulse-layer": true,
      "main-fort-stockton-pulse-layer": true,
      "texas-blocks-line-layer": true,
      "texas-blocks-hover-layer": true,
      "texas-block-fill-layer": true,
      "key-infra-hs-layer": true,
      "main-path-b-layer": true,
      "main-path-aa-particles-layer": true,
      "data-centers-fill-layer": true,
      "data-centers-line-layer": true,
      "aquifer-zones-fill-layer": true,
      "aquifer-zones-outline-layer": true,
      "texas-blocks-fill-hover-layer": true,
      "texas-block-fill-hover-layer": true,
      "aquifer-zones-hover-outline-layer": true,
      "aquifer-zones-hover-layer": true,
      "data-centers-point-layer": true,
      "data-centers-circles-fill-layer": true,
      "data-centers-circles-5mi-fill-layer": true,
      "new-major-aquifers-fill-layer": true,
      "new-major-aquifers-outline-layer": true,
      "supply-layer": true,
      "water-layer": true,
      "sources-circle-fill-layer": true,
      "sources-circle-layer": true,
      "sources-layer": true,
      "sources-label-layer": true,
      "sources-pulse-layer": true
    },
    "customState": {
      "transmissionFocus": true,
      "analysisType": "transmission",
      "timestamp": 1753975060333
    }
  }
];

/**
 * Load default scenes if no scenes exist
 */
export function loadDefaultScenes() {
  try {
    // Check if scenes already exist
    const existingScenes = localStorage.getItem('transmissionScenes_v1');
    
    if (!existingScenes || JSON.parse(existingScenes).length === 0) {
      
      
      // Load default scenes
      localStorage.setItem('transmissionScenes_v1', JSON.stringify(DEFAULT_SCENES));
      
      

      
      // Dispatch event to notify app
      window.dispatchEvent(new CustomEvent('defaultScenesLoaded', { 
        detail: { sceneCount: DEFAULT_SCENES.length } 
      }));
      
      return true;
    
      return false;
    }
  } catch (error) {
    console.error('❌ Failed to load default scenes:', error);
    return false;
  }
}

/**
 * Force reload default scenes (overwrites existing)
 */
export function forceLoadDefaultScenes() {
  try {
    
    
    // Load default scenes (overwrites existing)
    localStorage.setItem('transmissionScenes_v1', JSON.stringify(DEFAULT_SCENES));
    
    
    console.log(`📊 Loaded ${DEFAULT_SCENES.length} default scenes`);
    
    // Dispatch event to notify app
    window.dispatchEvent(new CustomEvent('defaultScenesLoaded', { 
      detail: { sceneCount: DEFAULT_SCENES.length } 
    }));
    
    return true;
  } catch (error) {
    console.error('❌ Failed to force load default scenes:', error);
    return false;
  }
}

/**
 * Get default scenes data
 */
export function getDefaultScenes() {
  return DEFAULT_SCENES;
}

/**
 * Check if default scenes are loaded
 */
export function hasDefaultScenes() {
  try {
    const existingScenes = localStorage.getItem('transmissionScenes_v1');
    if (!existingScenes) return false;
    
    const scenes = JSON.parse(existingScenes);
    return scenes.length > 0;
  } catch (error) {
    return false;
  }
}

// Auto-load default scenes when module is imported
if (typeof window !== 'undefined') {
  // Load on next tick to ensure app is ready
  setTimeout(() => {
    loadDefaultScenes();
  }, 100);
} 